### ISSUE TITLE
Make todo list of issues which should be done on bootstrap stage with links how should it be done

### ISSUE THREAD

**Issue by hyzhak** [hyzhak/bot-story#260]
For example:

# on bootstrap
- [ ] change log
- [ ] bootstrap fb bot
- [ ] mind map of idea
- [ ] write down idea to README

# after bootstrap
- [ ] art: icon
- [ ] text: description
